### ISSUE TITLE
CRLF is \n or \r\n?

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#101]
It seems like we have two different definitions, is that accurate? If so which is preferred?

https://github.com/Lartu/ldpl/blob/master/src/ldpl_lib.cpp#L16 is `\n`

https://github.com/Lartu/ldpl/blob/master/src/ldpl.cpp#L283 is `\r\n`

**Comment by Lartu** [comment]
I think this https://github.com/Lartu/ldpl/blob/master/src/ldpl_lib.cpp#L16 is a leftover from the past that should be deleted. The correct CRLF definition is the one on ldpl.cpp line 283, `\r\n`.
