### ISSUE TITLE
Macros?

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#105]
This is probably a bad idea, but the asmjit conversation got me thinking about it a bit. 

One of the most powerful features in compiled languages like C and C++ are the macros/templates. Same for Lisp. 

LDPL could potentially allow users to extend the language at compile time, with no runtime performance penalty, by adding `line_like()`-style macros. 

This would allow LDPL to remain a super simple language at its core, while letting people create higher level abstractions for use in their own programs. 

Language features could be tested as macros, or packaged up and shared with other, before being added to the language. Or they could remain independent packages, allowing for a more modular design. Classic "function calls" with arguments can be faked and new syntax can be added to any program.

However, it would add a huge cognitive burden. Right now I can read any LDPL program and probably know what it does. With macros, that's not true. All sorts of other problems come with them too, not least of all the tooling difficulties.

Still, they could be fun. Here's one thought:

```
MACROS:
define "$num-var = $num-expr + $num-expr" as
    add $1 and $2 in $num-var
end define

define "puts $expr" as 
    display $expr crlf
end define

define data "$var is stack" as
    $var is number vector
    $var-length is number
end define

define "push $num-expr onto $num-vec" as 
    store $num-expr in $num-vec:$num-vec-length
    incr $num-vec-length
end define 

define "pop $num-vec in $num-var" as 
    if $num-vec-length is greater than 0 then 
        decr $num-vec-length
        store $num-vec:$num-var-length in $num-var
    else
        store 0 in $num-var
    end if
end define

define block "loop do" "$expr" "repeat" as 
    while 1 is equal to 1 do
        $expr
    repeat
end define

DATA:
s is stack 
n is number

PROCEDURE:
push 1 onto s
push 2 onto s
push 3 onto s
pop s in n
puts "n is " n
n = 1 + 1 
puts "1 + 1 is " n
loop do
    puts "Ctrl-C to exit"
repeat
```

Obviously, one could get pretty carried away. Adding new syntax (the dollar sign) is a bummer too. 

But wanted to throw it out there, or at least start a discussion and see if it's worth exploring other ways of extending the language beyond just defining `sub-procedures`.

**Comment by Lartu** [comment]
This would be beyond awesome! An alternative to this would be to implement some sort of functions, thought, but I guess the end result would be the same. What do you think? How hard would this be to implement?

**Comment by dvkt** [comment]
I don't think macros would be super difficult to implement, the hard part would probably be the error messages and understanding what's happening when something goes wrong. But I guess today you already have to deal with that a bit since the error is usually "malformed statement". Thankfully the syntax is so simple, so maybe it wouldn't be a huge problem. I can work on a branch and see how it turns out.

But functions would be really cool, too. Plus there we'd have less complexity because we're not adding this whole new "rewrite before compiling" step, and we could get stack traces. And you could call them from C/C++, potentially. What would they look like?

**Comment by Lartu** [comment]
You are of course more than welcome to try to implement any of those things! I should also try to get my hands dirty with some of that, but I've been super busy lately. Sorry for my late replies. I still have an email to answer to you, sorry about that as well.

I think functions would be easier to implement, as they would just be translated to C++. The only thing would be that in C++ parameters exist within the local scope and that in LDPL is not a thing. I was thinking, though, that it would be awesome that sub-procedures came each with two vectors (`localNumber` a NUMBER vector and `localText` a TEXT vector) that you could use within local access (and with that we could implement recursive functions!). So, maybe we could do the same thing with functions, and they could have a parameter vector or something like that.

The syntax... I don't really know. Maybe we could just add parameters to sub-procedures?

**Comment by dvkt** [comment]
> The syntax... I don't really know. Maybe we could just add parameters to sub-procedures?

I was gonna do something similar, but then I checked out how COBOL does it. I think you've been in there before because I recognize the `CALL` syntax, but the rest of it is really interesting too. It seems like instead of calling functions, in COBOL you call an entire `PROCEDURE:` section at once, defined something like:

```
PROCEDURE DIVISION USING LS-STUDENT-ID, LS-STUDENT-NAME.
   DISPLAY 'In Called Program'.
   MOVE 1111 TO LS-STUDENT-ID.
EXIT PROGRAM.
```

Then you call it with:

    CALL procedure-name USING variable-1, variable-2.

It could be kind of cool to merge functions with arguments and modules into one concept. Instead of each file's `PROCEDURE:` section being run automatically when included with `-i=`, maybe they become named and can be called? A little bit like Python's modules, as you mentioned in another thread.

Here's an imaginary PROCEDURE to convert a text word to uppercase:

```
$ cat upcase.ldpl
DATA:
word is input text

chars is text vector
char is text
out is text
n is number
len is number
code is number

PROCEDURE:
sub-procedure upcase-char
    get character code of char in code
    if code is greater than 96 then 
        if code is less than 123 then 
            subtract 32 from code in code
            store code code in char 
        end if
    end if 
end sub-procedure

split word by "" in chars
store index count of chars in len 
while n is less than len do
    store chars:n in char 
    call upcase-char
    join out and char in out 
repeat
store out in word
```

Maybe you load it in and call it like so:

```
$ cat main.ldpl
DATA:
t is text
IMPORT:
"upcase.ldpl" as upcase
PROCEDURE:
DISPLAY "Text to convert to uppercase: " 
ACCEPT t
CALL upcase USING t 
DISPLAY "Uppercased: " t crlf 
```

Each `DATA:` section would stop being global and become local to its `PROCEDURE:` section. The `IMPORT:` section could replace the `-i=` flag, and there would be `INPUT` variables that glue different procedures together. Sub-procedures would only be accessible inside their procedure, not global.

The `IMPORT:` section could also be a statement, which might be more natural:

```
$ cat main.ldpl
DATA:
t is text
PROCEDURE:
IMPORT "upcase.ldpl" AS upcase
DISPLAY "Text to convert to uppercase: " 
ACCEPT t
CALL upcase USING t 
DISPLAY "Uppercased: " t crlf 
```

Something to consider at least! One nice thing about an approach in this style is we don't have to add any punctation, like (parens) for function calls.

**Comment by Lartu** [comment]
> Don't let me pressure you, no rush or obligation on any responses!

Haha, no rush nor pressure, but I don't like to leave you hanging without any responses!

> It could be kind of cool to merge functions with arguments and modules into one concept. Instead of each file's PROCEDURE: section being run automatically when included with -i=, maybe they become named and can be called? A little bit like Python's modules, as you mentioned in another thread.

One thing I absolutely dislike from Python is that when you declare variables in one file, they aren't available on other files that included the former one.
I would like more some way of adding namespaces. Maybe in order to call a variable or procedure from other file you have to do something like what I said [here](https://github.com/Lartu/ldpl/issues/103#issuecomment-495957870).

What you are saying, though, is very interesting. I don't know what would happen with the DATA section of the included file.
Would it be local? Would it be added to the global scope? That's something very important to decide, for if you use, say, `i` in your
imported file, what would happen if I also used `i` in mine?

(All the data sections could be mixed though, we can use `filename/variable` or something like that to name variables in libraries
and that will be the end of it.)

> Each DATA: section would stop being global and become local to its PROCEDURE: section. The IMPORT: section could replace the -i= flag, and there would be INPUT variables that glue different procedures together. Sub-procedures would only be accessible inside their procedure, not global.

Oh, I see you replied that here! I love what you say! It's quite interesting. It could work!

I do really like it, it feels like ancient punched card libraries that added a single procedure to your code.
More dinosaur stuff, haha!

> The IMPORT: section could also be a statement, which might be more natural.

I just love this! This is a wonderful idea, I love the road you've taken with this!

**Comment by dvkt** [comment]
> I do really like it, it feels like ancient punched card libraries that added a single procedure to your code.
More dinosaur stuff, haha!

Okay great! Let me try this out when I can and see how it feels. I don't want to make things more difficult than they need to be for LDPL programmers, but I do think LDPL has an opportunity to explore new (old?) ways of structuring code, so this is exciting.

**Comment by Lartu** [comment]
> new (old?) 

HAHA :laughing: 

I agree with you. This could be something! Let me know if you do something! I don't think this'd make things more difficult than they need to be (but if it did, LDPL is a COBOL parody in some way, that wouldn't do harm, haha).
