### ISSUE TITLE
WAIT not working on windows

### ISSUE THREAD

**Issue by ZettaXZycho** [Lartu/ldpl#112]

**Comment by dgarroDC** [comment]
It's working for me, are you using MinGW? What happens when you use the statement?

**Comment by Lartu** [comment]
It's not working for me either. I'll check it out now.

**Comment by Lartu** [comment]
Fixed in the last commit!

**Comment by Lartu** [comment]
https://stackoverflow.com/questions/27497407/how-to-detect-gcc-threading-model-with-preprocessor
This should be implemented, in order to check the thread model under windows (at the moment we just check if the user is using windows or not, not the thread model).

**Comment by Lartu** [comment]
@dgarroDC, as it was working for you before my fix, could you please tell me if `WAIT` still works for you under Windows? (my MinGW installation doesn't use POSIX threads). If it does, I'll close this issue. Thanks!

**Comment by dgarroDC** [comment]
Yes, it's still working after the fix!

**Comment by Lartu** [comment]
Great, thank you very much for testing this! I'm closing this issue now.
