### ISSUE TITLE
Built in statements to work with CSVs

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#119]
@fireasembler has written a wonderful [library](https://github.com/fireasembler/csvlib) to read and write to and from CSV files in LDPL. I think it would be wonderful to add statements to the language that mimic these features. Something like:

`LOAD CSV <filename> IN <text list> USING DELIMITER <delimiter> AND STRING DELIMITER <string delimiter>`

And some sort of `WRITE CSV`. What do you think?

**Comment by dgarroDC** [comment]
I'm not sure, I think it's a little too specific thing to add to the language and having that library is enough. :thinking:

**Comment by fireasembler** [comment]
I agree with @dgarroDC on this one

**Comment by Lartu** [comment]
> I'm not sure, I think it's a little too specific thing to add to the language and having that library is enough. :thinking:

True, but nevertheless people work with CSVs and I think it would be nice to have builtin commands for this. The other thing we could do, though, is start working on a Standard Library :thinking: or making packages for some future package manager.

**Comment by fireasembler** [comment]
I'd be up for creating a standard library. A packaging system could be great. Do you have a format already in mind or can we make up our own?

**Comment by Lartu** [comment]
> I'd be up for creating a standard library.

Wonderful!

> Do you have a format already in mind or can we make up our own?

At the moment, nothing planned. I was just thinking of a tool that would let you `lpm get <library name>` and that library would be downloaded into your working directory, so you could `ldpl -i` it. In the future, when we add `INCLUDE` statements I'd like multi-file libraries to be `tar`-ed and those libraries would be extracted in its own folder so one could `INCLUDE "folder/mainLibraryFile.ldpl"` or something like that.
