### ISSUE TITLE
Add multiline strings

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#12]

**Comment by dvkt** [comment]
I was wondering about this feature today. Did this get added or did you decide against it?

It would be really useful for stuff like email templates, HTML templates, madlibs, maybe even embedding C/C++ directly in LDPL like https://github.com/JuliaInterop/Cxx.jl.

**Comment by Lartu** [comment]
I decided against it just because I think it would be too hard to implement with little benefit. LDPL lines are all split when loading the file, so some shenanigans would have to be done to accept multiline strings.

**Comment by Lartu** [comment]
(I mean, if you **want** to implement them, I woun't oppose, of course!)

**Comment by dvkt** [comment]
Okay makes sense thanks!
