### ISSUE TITLE
FOR EACH loops

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#120]
It would be wonderful to have `FOR EACH` loops in LDPL to iterate through every element in a MAP or a LIST. Maybe something like:

```python
FOR EACH <var of the same type of the list> IN <list> DO

REPEAT
```

**Comment by dgarroDC** [comment]
I like this!

What about also using `REPEAT` instead of `NEXT` in `FOR - FROM - TO - STEP - DO`?  I prefer if we use the same word in all loop statements.

**Comment by Lartu** [comment]
I'd love that! Better and simpler to understand.

**Comment by dgarroDC** [comment]
Done!

**Comment by Lartu** [comment]
Thank you very much!

**Comment by dgarroDC** [comment]
Wait, this issue isn't about that, haha.

**Comment by Lartu** [comment]
AHAHA sorry, yes, my bad.

**Comment by Lartu** [comment]
Thank you!

**Comment by Lartu** [comment]
@dgarroDC please don't forget to document this!

**Comment by dgarroDC** [comment]
Done!

**Comment by Lartu** [comment]
Thank youuuu! <3
