### ISSUE TITLE
LDPL Standard Library

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#126]
I've created the [LDPL Standard Library](https://github.com/Lartu/ldpl-std). It's a collection of library files (called *briefcases* by suggestion of @dgarroDC), each with sub-procedures that deal with a particular thing (for example, the already created `std-lists.ldpl` has a lot of useful LIST sub-procedures). I'm just adding this issue here so you know this exists. Any contribution is greatly appreciated!

Specially, @fireasembler I'd like to ask you to create something like `std-os.ldpl` following the format of `std-lists.ldpl` and add the sub-procedure you had written to detect the OS the user was running there. This could be very useful in the future!

Please bear in mind that the standard library uses https://github.com/Lartu/ldpl/pull/124, so you'll have to pull from Damián's branch and install that version of LDPL at the moment (unless that by the moment you read this that branch has already been merged into master).

Thank you all and have a nice day!

**Comment by fireasembler** [comment]
will do! any specific things you want to see in the std?

**Comment by Lartu** [comment]
At the moment I hadn't thought of any. Just anything you come up with!

**Comment by Lartu** [comment]
Closed as it belongs in https://github.com/Lartu/ldpl-std/issues/3
