### ISSUE TITLE
we should try to get ldpl on linguist

### ISSUE THREAD

**Issue by fireasembler** [Lartu/ldpl#128]
[linguist](https://github.com/github/linguist) is the tool github uses to mark what language each file in a repository is and in order to provide syntax coloring to code files.

registerting ldpl on that might make it a tad more accessible and give us a small push.

**Comment by dgarroDC** [comment]
This would be awesome. In fact, I thought about this a while ago, but I think there was some requirement about the language usage on GitHub repos or something like that.

**Comment by dgarroDC** [comment]
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by Lartu** [comment]
> This would be awesome. In fact, I thought about this a while ago, but I think there was some requirement about the language usage on GitHub repos or something like that.

That's a pity though :(

**Comment by fireasembler** [comment]
It's not a requirement IIRC, it's a _prefference_. The part that actually scared me in their rules is that they don't accept GPLv3 licensed grammars

**Comment by Lartu** [comment]
Oh but that's not a problem. LDPL grammar is MIT licensed if anything (can you even license a grammar??), the compiler is what is GPLv3. So no problem there.

**Comment by Lartu** [comment]
https://softwareengineering.stackexchange.com/questions/178776/what-constitutes-a-programming-language-and-how-does-one-copyright-a-programming

Apparently you cannot license a language, only a compiler. What do they mean by licensed grammars?

**Comment by dgarroDC** [comment]
They mean the licence of the repo with the grammar you upload. 

But I think they expect at least 200 usages, see https://github.com/github/linguist/pull/4552 for example, maybe we should wait for now.

**Comment by fireasembler** [comment]
@Lartu I think we can close this issue for now and reopen it once ldpl gets some more adoption.

**Comment by Lartu** [comment]
Ow well :( Let's keep this in mind though!

**Comment by omdxp** [comment]
Any updates on this?

**Comment by Lartu** [comment]
Not on my end, no.
