### ISSUE TITLE
SPLIT BY multiple chars

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#131]
`SPLIT BY X FROM - IN <vector>` and `SPLIT BY X FROM - IN <list>` do not work if the length of X is greater than 1 (does work with 0, as specified in the documentation though). An error should be raised if the length of X is greater than one (bear in mind that X might be an utf8 literal) or we should allow splitting by multiple characters, but at the moment if you try to split a text by something lengthier it will just return a list or vector containing the original string.

**Comment by dgarroDC** [comment]
> or we should allow splitting by multiple characters

I implemented this.

**Comment by Lartu** [comment]
Wonderful, thank you very much for your contribution!
