### ISSUE TITLE
SQLite Library

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#139]
It would be nice to have a SQLite library to interface SQLite with LDPL. I've found [this library](https://github.com/iwongu/sqlite3pp) that seems to do just that. Maybe something can be done with it.

**Comment by xvxx** [comment]
I think this is another one where we’d benefit from custom types. You could do `RUN SQL QUERY “blah” IN var` where `var` would be a special SQL result type that you can run other statements against. Like the # of rows returned, names of fields as a list of strings, etc. Possibly.

**Comment by Lartu** [comment]
Yes, that'd be lovely :thinking:
