### ISSUE TITLE
Document multicontainers

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#140]
There's a big issue with LDPL right now: we cannot have lists of lists, nor maps of lists nor lists of maps nor any compound type. If we had that, the language would be way more useful and a lot bunch more interesting libraries could be coded for it (and thus, used more in real-world scenarios).

I imagine the syntax would be something like:

`compoundFoo is number list map`

meaning that compoundFoo is a map<list<number>>, and so we could access its members like

`compoundFoo:"someKey":4 #container:key:index`

**Comment by dgarroDC** [comment]
I agree that LDPL needs this, but there's a problem of ambiguity in the accessing syntax with what we already have, `A:B:C` could be like `A[B[C]]` (LDPL current syntax) or like `(A[B])[C]`.

**Comment by Lartu** [comment]
Added in https://github.com/Lartu/ldpl/commit/75f7f70833760e88f46c2e77631f73d749d3d0a4. Documentation still due.
