### ISSUE TITLE
variable_type not working properly

### ISSUE THREAD

**Issue by dgarroDC** [Lartu/ldpl#142]
The [`variable_type` function](https://github.com/Lartu/ldpl/blob/d459628c32b8bfe42cfe2eae7fe34f352797a3a3/src/ldpl.cpp#L1986) doesn't work correctly when you access a container using another accessed container like an index (for example, in `foo:bar:0:1`). This must be fixed.

**Comment by Lartu** [comment]
Fixed in 34fee0944f6ce005b8e3ab3b13e19f3834f17083! Thank you very much!
