### ISSUE TITLE
multi-containers for each

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#146]
I don't know if the for each loops work with multi-containers. I think they don't, but this should be checked. If they don't, and it's possible, it would be nice to make them work. But that's complicated, we could just keep them working with scalar values and add that to the documentation.

I tag you @dgarroDC because you wrote the for each statement, in case you want to add something.

**Comment by dgarroDC** [comment]
They don't work with multi-containers right now. And I think many others statements like `CLEAR` have this issue too, because functions like `is_list` aren't accepting multi-containers.

**Comment by Lartu** [comment]
Yes! You are right. I have just fixed that.

**Comment by Lartu** [comment]
In fact, none of the LIST and MAP statements worked on multicontainers, but that has been fixed.

**Comment by Lartu** [comment]
https://github.com/Lartu/ldpl/blob/2aabd3303ff897973a68453485e47c3ed804f756/src/ldpl.cpp#L1132

Here I have an example of how to create a C type for a multi-container variable. I link that because I think it may come in handy when adapting FOR EACH loops for multi-containers.

**Comment by Lartu** [comment]
It would be nice to solve this, but if this cannot be solved (or that's too hard) it would suffice to add an error message saying "you cannot use for each with multicontainers" or something like that.

**Comment by dgarroDC** [comment]
`FOR EACH` now works with multicontainers!

**Comment by Lartu** [comment]
Woah! Wonderful! Thank you for this, @dgarroDC! :tada:
