### ISSUE TITLE
Nested map usage example

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#161]
I'm sure I'm just missing something, but I can't figure out how to get nested maps to work. 

Here is the example from https://docs.ldpl-lang.org/data/:

````coffeescript
data:
    listOfMaps is text map list
    listOfLists is text list list
procedure:
    push map to listOfMaps
    store "Hello!" in toListOfLists:0:"hi!"
    # Pushes a map to listOfMaps and then stores
    # the value "Hello!" in the key "hi!" of the pushed map
    push list to listOfLists
    push "Hello!" toListOfLists:0
    # Pushes a map to listOfLists and then pushes
    # the value "Hello!" at index 0 of the pushed list
````

Obviously there is a typo as `toListOfLists` doesn't exist. But if I change it to `listOfMaps`:

````coffeescript
data:
    listOfMaps is text map list

procedure:
    store "Hello!" in listOfMaps:0:"hi!"
````

This compiles but produces a runtime error:

````
$ ./ldpl map.ldpl
* Loading map.ldpl
* Compiling map.ldpl
* Building map-bin
* Saved as map-bin
* File(s) compiled successfully.
$ ./map-bin
Runtime Error: LIST index 0 out of range [0, 0)
````

Am I missing a step here? The documentation for nested lists works for me when I test it.

**Comment by dgarroDC** [comment]
You need to add the `push map to listOfMaps` line, otherwise `listOfMaps` will be empty and you can´t access its first element (`listOfMaps:0`) because it doesn´t exist.

**Comment by dvkt** [comment]
Oh, I was literally missing a line! Somehow I knew it but also didn't know it, ha. Thank you! Sorry about that.

So when I fix my copy/pasta, this works:

````coffeescript
data:
    listOfMaps is text map list

procedure:
    push map to listOfMaps
    store "Hello!" in listOfMaps:0:"hi!"
```

But what about `text list map`? 

````coffeescript
data:
    mapOfLists is text map list
procedure:
    push "hi" to mapOfLists:"A"
````

I tried to `push` a `list` and to `store` a `list` but neither of them worked for me. I'm clearly missing another line but I'm not sure what.

**Comment by dvkt** [comment]
Oh, I was literally missing a line! Ha, I knew it. Thank you.
