### ISSUE TITLE
Valid multicontainer access treated as invalid (and vice-versa)

### ISSUE THREAD

**Issue by dgarroDC** [Lartu/ldpl#166]
This doesn´t compile (`Malformed statement`):
```
data:

a is number map map
b is number map
c is number

procedure:

display a:b:c:b:0
```

If we replace the `c` with `0` it works.

Maybe the problem is here:
https://github.com/Lartu/ldpl/blob/eb14e2f343f86d0124a6d6b97da7b75c7cad56a6/src/ldpl.cpp#L2081
Should we check if the token is any scalar expression (instead of just a literal)?

I also found that this passes the LDPL to C++ stage (but throws an error compiling the C++ code because of the `VAR_A[VAR_A]` expression):
```
data:

a is number map

procedure:

display a:a
```

**Comment by Lartu** [comment]
@dgarroDC I see this was marked as fixed in a commit. Shall I close this ticket?

**Comment by Lartu** [comment]
Wonderful! Thank you very very very very much for fixing this! <3
