### ISSUE TITLE
Remove PHP dependencies

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#167]
At the moment in order to properly build LDPL with a man file you have to have PHP installed on your system. This requirement should be removed.

**Comment by dvkt** [comment]
We can probably do this with LDPL now :+1: 

It would also be good to eventually list every dependency needed to build or develop LDPL in the README or somewhere, like the version of `make` that is known to work.

**Comment by Lartu** [comment]
100% agreed! Also yes, the dependency list is a great idea.
