### ISSUE TITLE
Is "argv" a good name?

### ISSUE THREAD

**Issue by saper** [Lartu/ldpl#178]
I was surprised to see "argv" mentioned in the documentation - this is not quite "plain" English... something else, like "program parameters", maybe?

**Comment by xvxx** [comment]
Yes it’s a bit cryptic, isn’t it? Apparently it originally stood for “argument vector” back in the day.

Maybe just “arguments”? I doubt that variable is used often in regular code, and I think LDLP will let you redefine and reuse it anyway if you want.

Side note: I believe that, technically speaking, “parameters” are the names and types of the variables used when defining a function, while “arguments” are the values of those parameters when the function is invoked. So I think we should try to keep it to something arg-related here for accuracy.

**Comment by Lartu** [comment]
Yes, it's a bit cryptic. Maybe we should rename it in future, major, non-backwards-compatible releases of the language, but if we were to change it right now we might break a lot of libraries and code, and that would be nasty.

**Comment by saper** [comment]
Sure, I'm just getting to learn the language; maybe we'll find more stuff like this in the meantime - thank you!

**Comment by Lartu** [comment]
Thank you for telling us about this!
