### ISSUE TITLE
Do ldpl identifiers (or sentence words) support uf8?

### ISSUE THREAD

**Issue by FireofGods** [Lartu/ldpl#190]
This is more of a question than an issue, but does ldpl support utf8 or is it an ascii-only language?

**Comment by Lartu** [comment]
Hi there! Yes, they should without a problem. I will check to make sure though...

**Comment by Lartu** [comment]
```coffeescript
data:
המבורגר is number
バーガー is number

procedure:
store 20 in המבורגר
store 30 in バーガー
display המבורגר " + " バーガー " = " 
add バーガー and המבורגר in המבורגר
display המבורגר "!" lf
```

Works perfectly!

**Comment by FireofGods** [comment]
I should have probably asked this question a bit differently: is an alternative implementation of ldpl expected to accept **case insensitive**  utf8 identifiers.

The problem is not specifically the utf8 identifiers, but the fact that lower/upper casing utf8 is kinda hard (or, at least, much harder than ascii).

**Comment by Lartu** [comment]
Ahh, I get it. You know, this is something that never crossed my mind 🤔 We are using the http://www.cplusplus.com/reference/cctype/toupper/ function to transform the source code to uppercase, so I don't believe `ááá` is the same variable as `ÁÁÁ`. So I guess no, that's not expected. I should add that to the documentation, thank you!

**Comment by Lartu** [comment]
I will be closing this issue now. Feel free to reopen it if you need.
