### ISSUE TITLE
Hi, I would like to start contributing to this language.

### ISSUE THREAD

**Issue by KTSnowy** [Lartu/ldpl#196]
I'm not sure where to start and if there anything that I could do to help, I've read that people wanted to implement ANTLR and WebAssembly on LDPL, so I was wondering if it would be possible for me to try working on those.

I've looked a little at [Cloudflare's cobweb repo](https://github.com/cloudflare/cobweb), and LDPL has some similarities with gnuCOBOL in the sense that it compiles to C (C++ for LDPL), and cobweb uses Emscripten to compile the C code to WebAssembly (It also allows to compile C++ into wasm), so it could be possible to modify/rewrite it to compile LDPL into wasm.

**Comment by Lartu** [comment]
Hi there! People want to implement ANTLR and WebAssembly on LDPL? Or LDPL on Antlr and WebAssembly? If it's the former I'm more than surprised!

Yes, you can work in anything you want. Anything that contributes to the LDPL project will be reviewed and most probably accepted!
