### ISSUE TITLE
Man file should be compiled using LDPL

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#205]
Compiling the LDPL man file currently requires PHP to be installed in the host system. This shouldn't be the case, as LDPL would be already installed on the system by this point, so LDPL could be used to build the man file.

**Comment by xvxx** [comment]
I started looking at this today. If we want to do a 1:1 conversion, we are going to need #149 since the php script uses `preg_replace()`. But maybe those `REPLACE` statements can be rewritten without regex, I haven't looked too closely yet.

**Comment by Lartu** [comment]
On one hand, you are right. On the other, maybe we should rework the docs into a one-page HTML file that's also easier to convert into a man file 🤔
