### ISSUE TITLE
Copy vectors

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#25]
The spec says `STORE NUMBER-VAR or NUMBER or TEXT-VAR or TEXT IN NUMBER-VAR or TEXT-VAR` so vectors are not included. Are the plans to keep it that way?

I get `LDPL Error: Malformed statement (copy-v.lsc:9)` when running this program:

```cobol
DATA:
v1 is text vector
v2 is text vector

PROCEDURE:
store "En" in v1:0
store "To" in v1:1

store v1 in v2

**Comment by Lartu** [comment]
Hi there! Yes it is, I believe one shouldn't mix values and collections, it's just messy. A "copy vector x to y` could be added though. One should take care tp free the memory though.

**Comment by dvkt** [comment]
+1: good to know this, thank you!
