### ISSUE TITLE
Define Source Code Conventions

### ISSUE THREAD

**Issue by VictorSCushman** [Lartu/ldpl#29]
Looking at the source code there seems to be a mix of conventions, particularly in `src/ldpl.cpp` about indentation, brace placement, naming, etc.

While probably not a high priority issue, having standard guidelines to follow or having a `.clang-format` that could be run would be useful to contributors.

**Comment by Lartu** [comment]
This is right! I actually wasn't really expecting anybody to contribute to LDPL so I didn't pay much attention to my coding style, but yes. Something like that should and will be done.
