### ISSUE TITLE
Incorrect Compiled On Date

### ISSUE THREAD

**Issue by VictorSCushman** [Lartu/ldpl#31]
For some reason the 'compiled on' date displayed by the `ldpl` executable is behind by exactly one day.

Steps to reproduce the issue:
```sh
~/code/ldpl[master]$ date
Tue Mar 19 13:58:42 EDT 2019
~/code/ldpl[master]$ cd src
~/code/ldpl/src[master]$ make
g++ -g ldpl.o -o ldpl -static-libgcc -static-libstdc++
~/code/ldpl/src[master]$ ldpl --version
This is LDPL 19 version 2.1.1

Copyright 2018-2019, Martín del Río

Standard and documentation can be found on ldpl.lartu.net.
Source code can be found at https://github.com/lartu/ldpl.

LDPL may be copied only under the terms of the GNU General Public License 3.0.

Compiled on Mon Mar 18 14:53:28 EDT 2019
```

Information about the machine the error occured on:
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
~$ uname -a
Linux vsc 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Lartu** [comment]
Hmm weird... Does the `date` command on your shell return the date minus one day? The LDPL makefile just calls `date`, I bet the error's there.

**Comment by VictorSCushman** [comment]
Just tested.
My `date` command is returning the correct date.
And I just use bash so there are no surprises there.

Does the `date` command build the correct data into the executable when you build on your machine @Lartu?

![Screenshot at 2019-03-30 17:54:33](https://user-images.githubusercontent.com/19331916/55282161-1ac44600-5315-11e9-9281-85a0dd966d02.png)

**Comment by dvkt** [comment]
I tested this on a few machines and it worked for me on all of them. The date in `ldpl -v` matches the date from when I run `date`.

**Comment by VictorSCushman** [comment]
I guess it must be something on my machine then.
I just tested again and got the same issue, exactly one day behind with the same date, but if @dvkt and @Lartu don't seem to be having problems on other machines then I am guessing it would be something with my OS or `make`.

**Comment by dvkt** [comment]
From [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html):

> The program used as the shell is taken from the variable SHELL. If this variable is not set in your makefile, the program /bin/sh is used as the shell.

Is there any chance your normal shell and the shell being used in the makefile's `$(shell date)` are different, or have different $PATHs? Or something in your user shell environment?

Maybe see if this is working as expected when you run it directly:

    /bin/sh -ec date

**Comment by Lartu** [comment]
The date format (along with `-v` and `-h`) has been changed in the last commit. If something wasn't working fine before, it should now.
