### ISSUE TITLE
LDPL generated binaries are not static

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#38]
I tried compiling a simple LDPL program on a `linux-arm` machine and, while it compiled and ran, it wouldn't run on a different `linux-arm` machine. I got this error:

```
$ ./hi-arm 
./hi-arm: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./hi-arm)
```

Adding `compile_line+=" -static-libgcc -static-libstdc++ ";` to `ldpl.cpp` and rebuilding the compiler fixed it:

```
$ ./hi-arm 
hi, arm!
```

However the binary size balloons from 90K to 1.5M.

Should LDPL programs be static, like the compiler itself? I think so yea?

**Comment by Lartu** [comment]
I agree very much with you, everything would be more consistent if they were static. I'm accepting your pr right now! Thank you!

**Comment by dvkt** [comment]
😃
