### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#41]
LDPL should really support expressions. It's very cumbersome to have to use
```
MULTIPLY someVar BY someConstant IN temp_var
ADD initialValue TO temp_var in TEMP_var
```
to do `initialValue + someVar * someConstant`. Given that LDPL compiles to C++, adding expressions to the language should be fairly easy. I'm not saying that `IF` statements or `WHILE` statements should support them (it would be nice, though), I'm saying that there should be some statement like
```
IN var SOLVE EXPRESSION initialValue + someVar * someConstant
```

**Comment by dvkt** [comment]
Maybe `IN var SOLVE MATH initialValue + someVar * someConstant`? Since `EXPRESSION` is kind of ambiguous in programming languages? But maybe that's just because I'm a bad math student !

**Comment by Lartu** [comment]
That would be fine as well, yes! I think that's even clearer haha
