### ISSUE TITLE
Mac OS binary for LDPL 3.0.0

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#45]
Hey @dvkt! Could you please -when you have the time, no rush- compile a macOS binary for LDPL 3.0.0 and upload it to the release? For a major release like this one, I'd be nice to have a binary for each major operating system and unfortunately I don't have a Mac made in the last ten years.

Thanks!

**Comment by Lartu** [comment]
(The release is [here](https://github.com/Lartu/ldpl/releases/tag/3.0.0))

**Comment by dvkt** [comment]
Awesome! Love the space dino!! 

I just uploaded the mac binary to https://github.com/Lartu/ldpl/releases/tag/3.0.0.

I also edited the post slightly to mention the new `ELSE IF` feature - don't forget about that one! That is pretty big too.

**Comment by Lartu** [comment]
Oh yes! The `ELSE IF` statement! I had forgotten about it, but you are right, it's pretty big!

Thank you very, very much for the binary! The release is complete.
