### ISSUE TITLE
Add a "wanted" section to the readme so people know what they can contribute with

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#48]
- emacs support
- sockets library / wrapper
- ~telegram bot library / wrapper~
- ~irc lib / wrapper~
- ~expression solver~

**Comment by dvkt** [comment]
- http server
- web framework
- gopher server 
- ldpl.lartu.net/play/ (or whatever), like https://play.golang.org/ and https://play.rust-lang.org/
- wasm target 
- "only pay for what you use" in LDPL, ie don't `#include` things the user doesn't use

**Comment by dvkt** [comment]
Could possibly do it as github issues too: https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels

> To attract new contributors, issues with labels that start with good first issue or help wanted are featured on the user dashboard, search, and topic pages.

**Comment by Lartu** [comment]
Yes! Yes, we should add some issues for new contributors. I'll get to it tomorrow.

**Comment by Lartu** [comment]
>ldpl.lartu.net/play/ (or whatever), like https://play.golang.org/ and https://play.rust-lang.org/

Hi @dvkt. I was just looking how could creating something like that be tackled and I haven't found anything. How would you do that? Any ideas?

**Comment by Lartu** [comment]
I found this https://blog.golang.org/playground.
