### ISSUE TITLE
Undocumented number to string conversion in vector sub-indexes

### ISSUE THREAD

**Issue by dgarroDC** [Lartu/ldpl#53]
Number vector sub-indexes are converted to strings [using std::to_string](https://github.com/Lartu/ldpl/blob/775a50daddfa021bee06eaa4a0dc5b7dbb753727/src/ldpl_lib.cpp#L35), leading to odd behavior. 

For example, [this example](https://gist.github.com/dgarroDC/d2adadca55858f7841bef5ddf1f209bf) displays "dinosaurio" and then "dragón" because 0 is converted to "0.000000", but the [reference](https://ldpl.gitbook.io/reference/variables-in-ldpl/usage-of-vectors) doesn't suggest this behavior.

**Comment by Lartu** [comment]
@dvkt  could we use the double to string without trailing zeros converter you used for `DISPLAY` with this issue?

**Comment by dvkt** [comment]
Yes that should fix it, I just made the change - try out the latest master. The example gist works for me now.

**Comment by Lartu** [comment]
Yes, that's it! Thank you!
