### ISSUE TITLE
Check if LDPL compiles statically for Windows

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#56]
@dvkt I think that on [this commit](https://github.com/Lartu/ldpl/commit/8316b5fcee75865cd30b9c47bc4fe4890d48f022), Windows hability to compile static binaries was broken. Since you added the `__linux__` check, do you by any chance know what the Windows equivalent would be?

Thank you!

**Comment by dvkt** [comment]
Should be fixed now yes, sorry! bb46cdf895a4a759b3ab7f38caf90d5fd522151d

Do you want to disable static builds on Android too? If so we probably make this change now, and not require using the `-ns` flag:

```diff
diff --git a/src/ldpl.h b/src/ldpl.h
index 71fafd6..fc09c57 100644
--- a/src/ldpl.h
+++ b/src/ldpl.h
@@ -12,7 +12,7 @@
 
 using namespace std;
 
-#if !defined(__APPLE__)
+#if !defined(__APPLE__) && !defined(__ANDROID__)
 #define STATIC_BUILDS 1
 #endif

**Comment by Lartu** [comment]
Ah, that could work, yes! Let's do that please! :smile:

**Comment by Lartu** [comment]
Hey, you uploaded a macOS binary! Awesome! Thank you very much!

**Comment by dvkt** [comment]
Okay doing that in #58 

> Hey, you uploaded a macOS binary! Awesome! Thank you very much!

Np! I will do that whenever I see a new release, if I am able to.

**Comment by Lartu** [comment]
Great! Thank you very much!
