### ISSUE TITLE
Add INCLUDE statement?

### ISSUE THREAD

**Issue by carbontwelve** [Lartu/ldpl#6]
Not sure if it's beyond the scope of this language given how its a bit tongue in cheek but it would be nice to have the ability to split a program up into _components_ and then include them aka the COBOL `INCLUDE` statement.

Given a directory structure like so:

```
.
└── src
    ├── main.ldpl
    ├── member-name.ldpl
    └── another-member-name.ldpl
```

You could within the `DATA` division allow an `INCLUDE` statement with similar syntax to COBOL:

```
DATA:
    INCLUDE member-name.ldpl
    INCLUDE another-member-name.ldpl
```

Or maybe have an additional `INCLUDE` division?

In either case the _include_ could act as a "copy-paste" merging the `DATA` and `PROCEDURE` divisions of the included source into the requesting file in the order in which they are included.

You could go one further and allow the `INCLUDE` statement in the `PROCEDURE` division to open the possibility of dynamic includes ;)

---

In adding includes it opens this language up to the entertaining possibility of libraries.

**Comment by Lartu** [comment]
Yes! It's been planned. At the moment, in fact, you can do `ldpl -i=file1.ldpl -i=file2.ldpl mysource.ldpl` to include file1.ldpl and file2.ldpl into mysource.ldpl. I will add the include statement as soon as I can though!

**Comment by carbontwelve** [comment]
Oh wow, I did not know that 👍 

I had been trying to think of interesting things I could build with this language for the fun of doing so and was reminded of the [1991](http://www.1-9-9-1.com/) web framework written in Forth. I'm not entirely sure it's possible to do in ldpl but it would be fun trying.
