### ISSUE TITLE
EXTERNAL SUB-PROCEDURE

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#60]
Hello there, @dvkt! Yesterday I added `EXTERNAL SUB-PROCEDURE` to the language. Essentially it's a way to declare functions that have been forward declared in C++, so I can call LDPL functions from C++.

So in C++ I can, for example, do this:
```
LDPL_SUBPROCEDURE();

void myFunction(){
  LDPL_VAR = 18;
  LDPL_SUBPROCEDURE();
}
```

And in LDPL I do:
```
data:
ldpl-var is external number

procedure:
external sub-procedure ldpl/subprocedure
  display "My number is " ldpl-var
end sub-procedure
```

I want to know what do you think about this. I made an IRC bot library for LDPL that I'll be uploading today and I needed this for that to work.

**Comment by dvkt** [comment]
This is awesome! :+1 :+1:

**Comment by Lartu** [comment]
Great! I'll leave it the way it is then :smile:
