### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#70]
A set of tests should be designed and setup along with a test script to test each new commit made to ldpl without much effort.

**Comment by Lartu** [comment]
Made to test*

**Comment by Lartu** [comment]
Done here:
https://github.com/Lartu/ldpltest

**Comment by dvkt** [comment]
Awesome! Was hoping they would be in LDPL! 🌟

**Comment by Lartu** [comment]
Ahahaha of course they are! :wink:
