### ISSUE TITLE
Label names

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#72]
Hey @dvkt I've found this:
```
bool is_label(string & token){
    return !isdigit(token[0]) && token[0] != ':' && token[0] != '"';
}
```

Why can't labels be numbers or start with : or be strings? Any particular reasons?

**Comment by Lartu** [comment]
I've fixed this. Now labels can be ***anything*** (?)

**Comment by Lartu** [comment]
(except have a single " in them)

**Comment by Lartu** [comment]
Labels can't have " in them anymore. This has all been fixed and the naming rules have been laid down [here](https://ldpl.gitbook.io/reference/naming-rules).

**Comment by dvkt** [comment]
Thank you for fixing and documenting that!

**Comment by Lartu** [comment]
Thanks to you for implementing them in the first place!El 25 abr. 2019 12:36, ʇʞʌp <notifications@github.com> escribió:Thank you for fixing and documenting that!
