### ISSUE TITLE
Names can't be numbers rule missing

### ISSUE THREAD

**Issue by dgarroDC** [Lartu/ldpl#74]
[Identifier Naming Schemes](https://ldpl.gitbook.io/reference/naming-rules) doesn't say anything about numbers as identifiers.

**Comment by Lartu** [comment]
You are right! I will fix that as soon as possible! Thank you!El 25 abr. 2019 13:50, Damián Garro <notifications@github.com> escribió:Identifier Naming Schemes doesn't say anything about numbers as identifiers.

**Comment by Lartu** [comment]
Fixed, thank you!
