### ISSUE TITLE
Binary number support

### ISSUE THREAD

**Issue by dvkt** [Lartu/ldpl#87]
It would be nice if LDPL could work with binary data. It would probably need two things:

1. Support for binary (`0b1010`) and hex (`0xFF`) number literals.
2. Support for bit operations.

Maybe the commands could look like this:
- `BITWISE A AND B IN C`
- `BITWISE A OR B IN C`
- `BITWISE A XOR B IN C`
- `BITWISE NOT A IN C`
- `BITWISE SHIFT A LEFT BY B IN C`
- `BITWISE SHIFT A RIGHT BY B IN C`
- `GET BIT AT N FROM A IN C`

Would this be a good candidate for the language or should it be an extension?

**Comment by Lartu** [comment]
I think this would be a great addition to the language! We can even add the symbols <, >, |, &, ¬ to represent shift left, right, or, and and not to solve math without changing almost anything of the current code!

**Comment by dvkt** [comment]
I think `solve math` will take some work because C/C++ doesn't allow bitwise on floating point numbers. 

So for the normal statements, we probably have to: 1. check if there's a fraction, 2. convert to int if no fraction (error if so), 3. perform bitwise operation, 4. convert back to float. This is how Lua does it according to [manual section 3.4.3](https://www.lua.org/manual/5.3/manual.html#3.4.3), since Lua also only has a single number type as far as the programmer is concerned.

However, if we add a sibling to `solve math` and name it something like `solve bitwise`, we can convert all input to int first.  So maybe something like: `IN var SOLVE BIT a | b`

**Comment by Lartu** [comment]
Oh right, we are using floating point numbers... I didn't think about that. I like what you are saying though. There's no real need to add it to `solve math` so don't really mind that.

**Comment by Lartu** [comment]
@dvkt should I close this? I don't really think that we'll end up using this in LDPL an in any case we could implement it as part of the standard library.
